### ISSUE TITLE
issue with Avoid

### ISSUE THREAD

**Issue by Exotic-Algorithms** [Screetsec/TheFatRat#301] opened 2018-07-30 16:00 UTC
When selecting Avoid, it fails to create the payload and exits with error code:

-                 REMAKE: Screetsec ( Edo -maland- ) 
      OPEN SOURCE :  NCC Group Plc ( http://www.nccgroup.com ) 
  DEVELOPED :  Daniel Compton, daniel dot compton at nccgroup dot com 
========================================================================
          METASPLOIT SHELL A.V. FOR BYPASS AV THIS VERSION 2.1  
========================================================================

TYPE THE DESIRED OUTPUT FILENAME : tester.7

TYPE THE DESIRED LABEL FOR THE AUTORUN FILES : t

 Your local IPV4 address is : 192.168.1.9
 Your local IPV6 address is : fe80::9eef:d5ff:fefd:35e6
 Your public IP address is : xx.xxx.xx.xx
 Your Hostname is : 2(SERVFAIL

  Set LHOST IP: 192.168.1.9
 
  Set LPORT: 443

[-] Generating Metasploit payload, please wait...

[ +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++   ]
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 362 bytes

==================================================================
   __            _                                    _  __  
  / _|_   _  ___| | ___   _  ___  _   _ _ __ ___  ___| |/ _| 
 | |_| | | |/ __| |/ / | | |/ _ \| | | | '__/ __|/ _ \ | |_  
 |  _| |_| | (__|   <| |_| | (_) | |_| | |  \__ \  __/ |  _| 
 |_|  \____|\___|_|\_\___ |\___/ \____|_|  |___/\___|_|_|   
                      |___/                                 
==================================================================

            ||||||||||||||
           =              \       
           =               |
          _=            ___/
         / _\           (o)\
        | | \            _  \
        | |/            (____)
         \__/          /   |
          /           /  ___)
         /    \       \    _)                        ) 
        \      \           /         TheFatRat      ( 
      \/ \      \_________/   |\___________________  ) 
       \/ \      /            |     ==== _______)__) 
        \/ \    /           __/___  ==== _/  
         \/ \  /           (O ____)\_(_/ 
                          (O _ ____) 
                           (O ____) 

================================================================= 

 1. Normal [ 400K payload ]  - [ fast compile ]  

 2. Stealth [ 1-2 MB payload ] - [ fast compile ] 

 3. Super Stealth - [ 10-20MB payload ] 

 4. Insane Stealth - [ 50MB payload ] 

 5. Desperate Stealth - [ 100MB payload ] 

 TYPE THE NUMBER IF YOU WANT :  5

[-] Desperate Stealth selected, please wait a few minutes

[-] Generating random seed for padding...please wait

[                                                                        [ 0                                                                      [ 01100                                                                  [ 011001                                                                 [ 0110011100                                                             [ 01100111001001                                                         [ 0110011100100100                                                       [ 01100111001001001                                                      [ 01100111001001001110                                                   [ 01100111001001001110111                                                [ 011001110010010011101110                                               [ 01100111001001001110111001                                             [ 0110011100100100111011100110                                           [ 011001110010010011101110011010                                         [ 01100111001001001110111001101010101                                    [ 011001110010010011101110011010101010101                                [ 01100111001001001110111001101010101010110                              [ 011001110010010011101110011010101010101101010                          [ 01100111001001001110111001101010101010110101001                        [ 01100111001001001110111001101010101010110101001010                     [ 01100111001001001110111001101010101010110101001010111                  [ 011001110010010011101110011010101010101101010010101110                 [ 0110011100100100111011100110101010101011010100101011100101             [ 011001110010010011101110011010101010101101010010101110010101           [ 0110011100100100111011100110101010101011010100101011100101010          [ 011001110010010011101110011010101010101101010010101110010101010        [ 0110011100100100111011100110101010101011010100101011100101010101010    ]
/root/TheFatRat/temp/build.c:106:15: error: redefinition of ‘padding’
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:2:15: note: previous definition of ‘padding’ was here
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:108:6: error: redefinition of ‘payload’
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:4:6: note: previous definition of ‘payload’ was here
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:228:6: error: redefinition of ‘comment’
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:100:6: note: previous definition of ‘comment’ was here
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:229:5: error: redefinition of ‘main’
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:101:5: note: previous definition of ‘main’ was here
 int main(int argc, char **argv) {
     ^~~~

[!] Something went wrong trying to compile the executable, exiting

Please note my FatRat version is 1.9.6

**Comment by peterpt** [comment] 2018-10-02 23:02
For your safety dont post again in any post your ip address , use xxx.xxx.xxx.xxx and we will know what you mean .

**Comment by PrOstOhAk** [comment] 2018-11-24 17:01
/root/TheFatRat/temp/build.c:33:15: error: redefinition of ‘padding’
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:2:15: note: previous definition of ‘padding’ was here
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:35:6: error: redefinition of ‘payload’
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:4:6: note: previous definition of ‘payload’ was here
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:98:6: error: redefinition of ‘comment’
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:27:6: note: previous definition of ‘comment’ was here
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:99:5: error: redefinition of ‘main’
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:28:5: note: previous definition of ‘main’ was here
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:104:15: error: redefinition of ‘padding’
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:2:15: note: previous definition of ‘padding’ was here
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:106:6: error: redefinition of ‘payload’
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:4:6: note: previous definition of ‘payload’ was here
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:163:6: error: redefinition of ‘comment’
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:27:6: note: previous definition of ‘comment’ was here
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:164:5: error: redefinition of ‘main’
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:28:5: note: previous definition of ‘main’ was here
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:169:15: error: redefinition of ‘padding’
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:2:15: note: previous definition of ‘padding’ was here
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:171:6: error: redefinition of ‘payload’
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:4:6: note: previous definition of ‘payload’ was here
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:240:6: error: redefinition of ‘comment’
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:27:6: note: previous definition of ‘comment’ was here
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:241:5: error: redefinition of ‘main’
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:28:5: note: previous definition of ‘main’ was here
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:246:15: error: redefinition of ‘padding’
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:2:15: note: previous definition of ‘padding’ was here
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:248:6: error: redefinition of ‘payload’
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:4:6: note: previous definition of ‘payload’ was here
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:282:6: error: redefinition of ‘comment’
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:27:6: note: previous definition of ‘comment’ was here
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:283:5: error: redefinition of ‘main’
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:28:5: note: previous definition of ‘main’ was here
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:288:15: error: redefinition of ‘padding’
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:2:15: note: previous definition of ‘padding’ was here
 unsigned char padding[]=
               ^~~~~~~
/root/TheFatRat/temp/build.c:290:6: error: redefinition of ‘payload’
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:4:6: note: previous definition of ‘payload’ was here
 char payload[] =
      ^~~~~~~
/root/TheFatRat/temp/build.c:379:6: error: redefinition of ‘comment’
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:27:6: note: previous definition of ‘comment’ was here
 char comment[512] = "";
      ^~~~~~~
/root/TheFatRat/temp/build.c:380:5: error: redefinition of ‘main’
 int main(int argc, char **argv) {
     ^~~~
/root/TheFatRat/temp/build.c:28:5: note: previous definition of ‘main’ was here
 int main(int argc, char **argv) {
     ^~~~

[!] Something went wrong trying to compile the executable, exiting

**Comment by peterpt** [comment] 2018-12-02 14:29
I got a different error using the normal payload 400k size , but my error was related to the icon used .
However it will be fixed in future , in mean while you have other options to test .
Watch this video and you may learn something as also fix common bugs .
Video have tests on different versions of windows and more .
https://www.youtube.com/watch?v=ZA7DCsGISmU

I will not close yet this issue until i check your options here and see the output .

Update to latest version of fatrat to solve some bugs .

**Comment by p-fabio** [comment] 2019-05-15 17:39
i get the same problem, any advice?

**Comment by peterpt** [comment] 2019-05-16 12:22
totally forgot this issue , probably is an error in the pump script witch is responsible to increase the size of the payload . I will test it on the weekend .

**Comment by p-fabio** [comment] 2019-05-16 17:01
i think the problem is that the script fatrat put in temp/build.c the code even if it's already full by the previous execution.
i executed 3 times i have 3 mains.

**Comment by peterpt** [comment] 2019-05-16 21:24
i will check when i get some time

**Comment by peterpt** [comment] 2019-10-05 23:30
1st - dont use names with dots like :
TYPE THE DESIRED OUTPUT FILENAME : tester.7  (i only notice it now)

2nd - delete your copy of fatrat and clone the new update and try again with a proper name like : tester7  instead tester.7

**Closed** 2020-03-02 14:26 UTC
