### ISSUE TITLE
cat powershell_attack.txt: file or directory not found

### ISSUE THREAD

**Issue by ebalo55** [Screetsec/TheFatRat#354] opened 2019-05-20 17:44 UTC
Running FatRat 1.9.5, as sudo on kali linux, last available version and trying to generate "PwnWinds" backdoor with "Create a bat file+Powershell (FUD 100%)", once set the options and all run i get the error:

cat powershell_attack.txt: file or directory not found

the execution block and throw me back to the sub menu where to chose the backdoor type.
(Note: using the same options with "Create exe file with C# + Powershell (FUD 100%)" or "Create exe file with apache + Powershell (FUD 100%)" generate **a file**.
I say a file because the second options generates only a non compiled file called "Program.cs" while the first one currently generate a working .exe file)

After a few test with all the scripts i've found none of the script under "PwnWind Version  v1.5" starts a reverse tcp meterpreter session, tested on windows 10.
Also some of them don't generate any executable or file of any type.

**Comment by peterpt** [comment] 2019-05-21 18:27
make sure you are using the latest repository .
The Program.cs file is a code file that will be compiled with monodenvelop-devel .
Delete your directory of fatrat and clone again , then run setup.sh .
The apache + powershell i have to check here when i get sometime .

**Comment by peterpt** [comment] 2019-06-01 18:30
Fixed in 1.9.7 .
Update your fatrat

**Closed by peterpt** 2019-06-01 18:30 UTC

**Comment by rajraushan18** [comment] 2020-03-03 20:20
it is showing the same problem in 1.9.7 and i am trying to generate "PwnWinds" backdoor with "Create a bat file+Powershell (FUD 100%)"

**Comment by KorvoA** [comment] 2020-05-21 03:45
I have the same error

**Comment by Guisardo** [comment] 2020-06-12 18:34
The problem is 1.9.7 seems to be that fatrat hides the output of trusted_2_7.py. That script is failing because msfvenom requieres bundler.
you can fix this using:
`gem installl bundler`
(can someone add that to the fatrat requirements checks?)

**Comment by Juan-Montes** [comment] 2021-12-20 20:32
Same problem I try to use option 1 of PwnWind with the bat and I get the error:


```
cat: powershell_attack.txt: The file or directory does not exist
rm: cannot delete 'unicorn.rc': The file or directory does not exist
mv: cannot perform `stat 'on' powershell_attack.txt ': The file or directory does not exist

```

I use Ips and not DNS for the reverse_tcp of the payload. I installed `gem install bundler` and it didn't work

**Comment by Nex026** [comment] 2021-12-26 21:50
pls how can i fix this, i'm not finding the solution

**Comment by DeepDash0x90** [comment] 2022-01-02 11:35
the problem was due to the static variable declare on "fatrat" code.

dave='python tools/trusted_2_6.py'

On my distribution kali the last version i don't have anymore python command.
I have python2 or python3, the fact is the script trusted_2_6.py use a specific command "reduce".
In Python 2, reduce() was a built-in function. However, in Python 3, it is moved to functools module.

So, i just correct the line :
dave='python2 tools/trusted_2_6.py'

restart the fatrat script and that will be done.

Enjoy.

**Comment by peterpt** [comment] 2022-01-25 14:48
works perfect here with python only , and python only still exists in most repositories specially kali rooling .
